### ISSUE TITLE
skeleton for dark mode

### ISSUE THREAD

**Issue by burhanahmeed** [Abdulqudus001/vue-skeleton-loader#7]
Hey, It's great component!! 

But when it comes to dark mode I got some problems because I can't change the background linear-gradient color.

```
.animation--wave::before {
    background: linear-gradient(90deg,transparent,rgba(255,255,255,.5),transparent);
    animation: wave 1.5s linear .5s infinite;
}
```
dark color with white wave didn't seem fit for me.
any tips?

**Comment by Abdulqudus001** [comment]
This has been fixed in the latest patch. You can now use the `wave-color` props to specify the color
